### ISSUE TITLE
Support for texts under Shadow DOM?

### ISSUE THREAD

**Issue by peace2000** [angezid/advanced-mark.js#12]
Hi @angezid, last year on `mark.js` repo https://github.com/julmot/mark.js/issues/458 you made a demo concerning highlighting texts under Shadow DOM.

Could you consider adding Shadow DOM support into your `advanced-mark.js` library?

Sample page that uses Shadow DOM: https://www.virustotal.com/

Thanks!

**Comment by angezid** [comment]
Actually, I'm already added basic support for Shadow DOM. See [Highlighting in shadow DOM](https://angezid.github.io/advanced-mark.js/doc-v2/shadow-dom.html).
![2023-04-17_195734](https://user-images.githubusercontent.com/82150610/232477718-5ccef2fd-a462-4774-bcff-9685a16f7c45.png)

**Comment by peace2000** [comment]
Thanks for adding support! I didn't realize the support was already there because the addon I use hadn't enabled it yet.

Anyway this can be closed :)
