### ISSUE TITLE
Missing diacritics letters (őŐ űŰ)

### ISSUE THREAD

**Issue by Juraj-Masiar** [angezid/advanced-mark.js#13]
Hello,
Could you please add these two letters support:
```
őŐ
űŰ
```
https://github.com/angezid/advanced-mark.js/blob/54a5a87c44f256f969f5dc573f57c132ddc5a4de/src/lib/regexpcreator.js#L342

Thank you! :)

**Comment by angezid** [comment]
They will be added in next release.
It seems to be a lot of characters are missing:

ÓÒŎÔỐỒỖỔǑÖȪŐÕṌṎȬȮȰØǾǪǬŌṒŌ̂̂ṐỎȌȎƠỚỜỠỞỢỌỘƟＯ
OÒÓỎÕỌÔỒỐỔỖỘƠỞỠỚỜỢÖØŌŐ

ÚÙŬÛǓŮÜǗǛǙǕŰŨṸŲŪṺỦȔȖƯỨỪỮỬỰỤṲṶṴɄＵ
UÙÚỦŨỤƯỪỨỬỮỰÛÜŮŪŰ

**Comment by Juraj-Masiar** [comment]
Oh, that's a lot! :)
There are other ways to remove diacritics, one using the `normalize` method:
https://stackoverflow.com/a/37511463/1376947
But it's also using regex so it's probably not as fast.

Anyway, thank you for the fix!
