### ISSUE TITLE
Support for virtual DOM

### ISSUE THREAD

**Issue by Nickersoft** [angezid/advanced-mark.js#9]
Hey @angezid,

Excited to see the progress this library has made over the past few months! Curious what your thoughts are about this [stale issue from the original repo](https://github.com/julmot/mark.js/issues/156) regarding adding support for virtual DOMs like JSDOM. 

For performance reasons, I'm looking at moving my MarkJS code to the BE, but currently can't because it still utilizes the global `document` object. I think maybe `document` could be an additional constructor prop that defaults to the global `document`? 

What do you think?

**Comment by angezid** [comment]
@Nickersoft currently I cannot say anything about supporting JSDOM.
Although, such approach can work maybe:
```js
const dom = new JSDOM(`...`);

const options = {
    diacritics : false,
    window : dom.window,
    document : dom.window.document,
    NodeFilter : dom.NodeFilter,
    . . .
};

const instance =new Mark(dom.window.document.querySelectorAll("selector"));
instance.mark('test', options);
```

**Comment by Nickersoft** [comment]
I think these options may have to be in the constructor, as you can't initialize Mark [without `document`](https://github.com/angezid/advanced-mark.js/blob/master/src/lib/mark.js#L38).

**Comment by Nickersoft** [comment]
Got a PR open! This change lazy-loads the `this.empty` so you can pass in a `window` object into the Mark options as you mentioned. Because `window` contains both `document` and `NodeFilter`, that's really all you need. I tested it via:

```javascript
const { JSDOM } = require('jsdom');

const Mark = require('./dist/mark.js');

const dom = new JSDOM('<!DOCTYPE html><html><body><p>this <i>is</i> a test</p></body></html>');
const mark = new Mark(dom.window.document.body);

mark.mark('this is a test', {
  acrossElements:true,
  window: dom.window
});

console.log(dom.serialize()); // <!DOCTYPE html><html><head></head><body><p><mark data-markjs="true">th<mark data-markjs="true">is</mark></mark> <i><mark data-markjs="true">is</mark></i> <mark data-markjs="true">a</mark> <mark data-markjs="true">test</mark></p></body></html>
```

Only thing is, I don't have any tests, as seeing this is Node-based I wasn't sure how to interop with the existing Karma tests. Not sure if you have any ideas on this front. Mentioned it in my PR.

**Comment by angezid** [comment]
@Nickersoft thanks for the PR. I have no doubt that virtual DOM can be useful.

I just	test your PR mark.js on 1 MB file, an array of 50 words as a single pattern, wrapped words ~24700.
Results:
Wrap time:
* Firefox ~0.3s
* Chrome ~0.37s
* JSDOM ~1,5s

File size becomes 1.8 MB.
Number of nodes: 24700 x 3 = 74100 - almost double the original file node number.

I just wonder how it could increase performance?
If take into account downloading time, parsing time, rendering time ...

**Comment by Nickersoft** [comment]
Interesting - wouldn't most of the performance tuning need to happen in how JSDOM implements the browser APIs? My guess is that the render engine of real browsers is more geared towards performance.
